### ISSUE TITLE
5.8 Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

### ISSUE THREAD

**Issue by jeremiahsherrill** [capistrano/laravel#50] opened 2019-03-28 17:41 UTC
Laravel 5.8

EBUG [9485c7aa] Command: cd /var/www/html/mcms/releases/20190328173840 && /usr/bin/env composer install --no-dev --quiet --prefer-dist --optimize-autoloader

 DEBUG [9485c7aa]       Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

trying to figure why it keeps failing

**Comment by keogblem** [comment] 2019-04-20 13:58
**I am having the same issue**. Please someone help

Note : I am only facing that error when running `composer update` online in my web hosting area, not on local server.

Thanks

**Comment by Gdzieniegdzie** [comment] 2019-04-20 15:49
Same problem.

**Comment by keogblem** [comment] 2019-04-20 21:11
Hi, I got a solution : this issue was due to one of my `config/` files that was empty (caused by error when uploading files to server), especially the `auth.php` which was there but empty (0 octets).

I figure that by running `php artisan clear` and i got error in the ServiceProvider at line 72 where merging config arrays `$this->app['config']->set($key, array_merge(require $path, $config));`

So, simple solution : **upload again your app files and make sure everything is place** 🙂

**Comment by codermahadi** [comment] 2019-06-24 07:01
Hi, I got a solution: this issue was due to one of my config/database.php that were empty (caused by an error when the composer updated).

I figure that by running **php artisan clear** and I got an error in the **Database [] not configure** DatabaseManage.php at line 252

So, simple solution: upload again your config/database.php files and make sure everything is place 🙂

**Comment by amirex128** [comment] 2019-07-07 05:02
> Hi, I got a solution : this issue was due to one of my `config/` files that was empty (caused by error when uploading files to server), especially the `auth.php` which was there but empty (0 octets).
> 
> I figure that by running `php artisan clear` and i got error in the ServiceProvider at line 72 where merging config arrays `$this->app['config']->set($key, array_merge(require $path, $config));`
> 
> So, simple solution : **upload again your app files and make sure everything is place** 🙂

nice

**Comment by saeedvaziry** [comment] 2019-09-22 15:10
For who has this issue :

I figured out problem is one of my configs. missing `return` or using a class that not exists.

Check `/config` and be sure that every thing is normal at there

**Comment by ikari7789** [comment] 2020-01-27 09:00
Seems unrelated to capistrano-laravel, so I'm closing this issue.

**Closed by ikari7789** 2020-01-27 09:00 UTC

**Comment by dericlima** [comment] 2020-04-27 16:29
Same issue here, on my case the `bootstrap/cache` directory wasn't with the right permissions. After updating the permissions everything started to work on the cloud server.

**Comment by zahidcserana** [comment] 2020-12-19 06:49
Try these command. In my case solved.

sudo chown -R $USER:www-data storage
sudo chown -R $USER:www-data bootstrap/cache
chmod -R 777 storage
chmod -R 777 bootstrap/cache

**Comment by muhammadali7768** [comment] 2020-12-29 17:16
i cloned a project from **github** and then run `composer install`. I got the following error.

`Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1`

I added `.env` file and run the `composer install` command. i got the same error again. Then i deleted  **composer.lock** file and **vendor** folder and run the `composer install` command again. The error was gone.

**Comment by nstone101** [comment] 2021-01-19 05:36
So is the general consensus on this a dir permissions issue or a an error or typo caused by uploading or clear function in artisan?  OR is this a problem with composer, or both? It seems there's alot of this with these latter rounds of composer versions that seem to be more apt for throwing the odd curveball and overwriting files and folders, not sure if it's related and was unsure of any origin docs or.a general definition or causal predisposition for this particular coded error. Thanks for input, will be back if no dice on the suggested fixes.It's odd because i've worked on several laravel projects in the last few days on the same environment/terminal used composer, worked fine, worked on another project which threw me an error i resolved with changing permissions on my cloud host ( digital ocean - laravel image, first time i've used their seemingly new pre- configured one click, i've always manually configured my linux environments, i'm wondering if you think that it could be the continuous integration script or something with my image relating to laravel projects that is changing permissions or overwriting configs? I should let this go. It's getting me too worked up.

**Comment by Hillaryudechukwu** [comment] 2021-02-16 20:53
**Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255**
I followed these steps to fix it
1. ran `php artisan clear` and got "PHP Fatal error:  Uncaught ErrorException: Method, ReflectionParameter::getClass() is deprecated in and not allowed in php 8.0"
2. My system had php version 8.0.0.4 and ReflectionParameter::getClass() is deprecated to in php version 8
3. I `brew unlink php@8.0.0.4` to downgrade my php and that was the fix

**Comment by nyachoto12** [comment] 2021-04-13 09:37
just run composer update it worked for me
